aragon/gov-ui-kit

- CHANGELOG.md
- src/components/input/walletInput.tsx
- On the delegation flow, we programmatically change the value of the WalletInput component by setting the connected address value. By doing this, the resolved values are not set to undefined as done on the `setValue` callback. This causes an indefinite `resolveValues` loop that set back and forth the old and new addresses when the old address has an ENS domain linked.
-   [x] Any dependent changes have been merged and published in downstream …
> fix: Fix WalletInput component when changing its value programmatically

- CHANGELOG.md
- src/components/headers/headerDao.stories.tsx
- src/components/headers/headerDao.tsx
- src/utils/addresses.tsx
As a user, I want to be able to access my DAO address name from the dashboard so that I don’t have to go all the way to the deposit flow (currently the fastest way to access the DAO address).
Task: [APP-2462](https://aragonassociation.atlassian.net/browse/APP-2462)
-   [x] I have updated …
> feat: APP-2462 added dao credentials dropdown in dao header

- CHANGELOG.md
- src/components/headers/headerDao.stories.tsx
- src/components/headers/headerDao.tsx
- updates the favorited (now following) icon and text
- updates the read more/less description icon
Task: [APP-2449](https://aragonassociation.atlassian.net/browse/APP-2449)
-   [x] I have updated the `CHANGELOG.md` file in the root folder of the package after the [UPCOMING] title and …
> Feat: APP-2449 - DAO Header Following status

- CHANGELOG.md
- package.json
- yarn.lock
- Update lint-staged to v15
-   Remove redundant `jackspeak` dependency resolution
> feat: Update lint-staged to v15

- CHANGELOG.md
- docs/codingGuidelines/libraryDependencies.mdx
- package.json
- yarn.lock
- Add documentation on how to handle library dependencies
- Relax `dependencies` and `peerDependencies` versions
Task: [APP-2619](https://aragonassociation.atlassian.net/browse/APP-2619)
-   [x] I have updated the `CHANGELOG.md` file in the root folder of the package after the [UPCOMING] …
> feat: APP-2619 - Feat document dependencies handling

- CHANGELOG.md
- package.json
- src/components/index.ts
- src/components/switch/index.ts
- src/components/switch/switch.stories.tsx
- src/components/switch/switch.test.tsx
- src/components/switch/switch.tsx
- yarn.lock
- Implements the `Switch` component
Task: [APP-2700](https://aragonassociation.atlassian.net/browse/APP-2700) …
> Feature: APP-2700 - Switch component

- CHANGELOG.md
- src/components/input/inputSearch/inputSearch.tsx
- Update the `InputSearch` component to fix its usage on SSR frameworks. We should only access the `window` object inside `useEffect` hooks or event callbacks so that the components don't crash when rendered on the server side.
Task: [APP-2816](https://aragonassociation.atlassian.net/browse/APP-2816) …
> fix: APP-2816 - Update InputSearch component to fix SSR

- CHANGELOG.md
- package.json
- Correctly set minimum Tailwind CSS version required (`size` utility classes have been only introduced on version 3.4) …
> fix: Correctly set minimum Tailwind CSS versions required by the library

- CHANGELOG.md
- src/components/input/index.ts
- src/components/input/inputTime/index.ts
- src/components/input/inputTime/inputTime.stories.tsx
- src/components/input/inputTime/inputTime.test.tsx
- src/components/input/inputTime/inputTime.tsx
- Implements the `InputTime` component
Task: [APP-2731](https://aragonassociation.atlassian.net/browse/APP-2731) …
> Feature: APP-2731 - Implement InputTime 

- CHANGELOG.md
- src/components/progress/index.ts
- src/components/progress/progress.api.ts
- src/components/progress/progress.stories.tsx
- src/components/progress/progress.test.tsx
- src/components/progress/progress.tsx
Implemented size property: specifically 'sm' with subsequent relabeled default as 'md'
-   updated 'md' (prev default at `h-[20p]`) to new visual height of `h-[8px]` per spec
-   removed padding from container per spec
Task: [APP-2815](https://aragonassociation.atlassian.net/browse/APP-2815) …
> feat: APP-2815 - implement `size` property with 'sm' + 'md' for Progress component

- CHANGELOG.md
- src/components/input/index.ts
- src/components/input/inputNumber/index.ts
- src/components/input/inputNumber/inputNumber.stories.tsx
- src/components/input/inputNumber/inputNumber.test.tsx
- src/components/input/inputNumber/inputNumber.tsx
- Implements the `InputNumber` component
Task: [APP-2729](https://aragonassociation.atlassian.net/browse/APP-2729) …
> Feature: APP-2729 - Implement Input Number component

- CHANGELOG.md
- src/components/input/inputText/inputText.tsx
Fixes an issue where props getting generated useInputProps hook was overriding local props in the input wrapper. In this case "overflow-hidden" was not getting applied back in the container.
Task: No ticket
> fix: style of InputText component with addon property

- CHANGELOG.md
- docs/installation.mdx
- package.json
- src/components/input/inputDate/inputDate.test.tsx
- src/components/input/inputDate/inputDate.tsx
- src/components/input/inputTime/inputTime.test.tsx
- src/components/input/inputTime/inputTime.tsx
- src/utils/index.ts
- src/utils/mergeRefs/index.ts
- src/utils/mergeRefs/mergeRefs.test.ts
- src/utils/mergeRefs/mergeRefs.ts
- Fix installation command to use the library without `tailwindcss`
- Add exports to properly use ESM/CJS library depending on the environment 
- Fix CJS build by removing ESM-only library `react-merge-refs`
-   [x] I have updated the `CHANGELOG.md` file in the root folder of the package after the …
> fix: Properly setup library exports and fix CJS build

- CHANGELOG.md
- src/components/link/index.ts
- src/components/radioGroup/index.ts
- src/components/radioGroup/radioCard/index.ts
- src/components/radioGroup/radioCard/radioCard.stories.tsx
- src/components/radioGroup/radioCard/radioCard.test.tsx
- src/components/radioGroup/radioCard/radioCard.tsx
- src/components/radioGroup/radioGroup/radioGroup.stories.tsx
- Implements the `RadioCard` component
- Fixes Storybook warning for the `ILinkProps` & `LinkVariant` exports
**Note**: Please review only after #86 has been merged.
Task: [APP-2736](https://aragonassociation.atlassian.net/browse/APP-2736)
-   [x] I have updated the `CHANGELOG.md` file in …
> Feature: APP-2736 - Implement RadioCard Component

- CHANGELOG.md
- src/components/heading/heading.stories.tsx
- src/components/heading/heading.test.tsx
- src/components/heading/heading.tsx
- src/components/heading/index.tsx
- src/components/index.ts
Implement <Heading /> component with design sizes for `size` prop (default 'h1') and custom `as` prop for semantic tag override.
Task: [APP-2878](https://aragonassociation.atlassian.net/browse/APP-2878)
-   [x] I have updated the `CHANGELOG.md` file in the root folder of the package after …
> feat: APP-2878 - Implement Heading component

- CHANGELOG.md
- README.md
- src/components/button/button.tsx
- src/utils/formatterUtils/formatterUtilsDefinitions.ts
Text correction on the following files:
```
README.md
src/utils/formatterUtils/formatterUtilsDefinitions.ts
src/components/button/button.tsx
```
and updated `CHANGELOG.md`.
This PR replaces PR #103
> fix: Typos on documentation and comments

- .storybook/preview.tsx
- .storybook/style.css
- CHANGELOG.md
- src/components/dialogs/dialog/dialogRoot/dialogRoot.tsx
- src/components/dialogs/dialogAlert/dialogAlertRoot/dialogAlertRoot.tsx
- src/components/dropdown/dropdownContainer.test.tsx
- src/components/dropdown/dropdownContainer.tsx
-  Fix usage of `Dropdown` component inside a `Dialog` component
-  Remove auto-focus to `Dropdown` trigger to avoid closing dialogs on `DropdownItem` click
- …
> fix: Usage of Dropdown component inside dialogs

- CHANGELOG.md
- package.json
- yarn.lock
- Update @typescript-eslint and eslint-plugin-storybook dependencies
- Set minimum required node version to 18.18.0 (required by `@typescript-eslint` v7)
the latest …
> feat: Update @typescript-eslint and eslint-plugin-storybook dependencies

- CHANGELOG.md
- index.css
- src/core/components/dialogs/dialog/dialogRoot/dialogRoot.tsx
- src/core/components/dialogs/dialog/dialogRoot/index.css
- src/core/components/dialogs/dialog/index.css
- src/core/components/dialogs/dialogAlert/dialogAlertRoot/dialogAlertRoot.tsx
- src/core/components/dialogs/dialogAlert/dialogAlertRoot/index.css
- src/core/components/dialogs/dialogAlert/index.css
- src/core/components/dialogs/index.css
- src/core/components/dropdown/dropdownContainer.tsx
- src/core/components/dropdown/index.css
- src/core/components/index.css
- src/core/index.css
- src/index.css
-   Introduce component customisations for the z-index property of the `Dropdown` and `Dialogs` components
Task: [APP-2761](https://aragonassociation.atlassian.net/browse/APP-2761)
-   [x] I have updated the `CHANGELOG.md` file in the root folder of the package after the [UPCOMING] title …
> feat: APP-2761 - Introduce z-index component customisations for the `Dropdown` and `Dialogs` components

- CHANGELOG.md
- rollup.config.js
- src/index.ts
- Fix library build to avoid bundling peer dependencies
- Remove export of module components until the Aragon App migrates to Wagmi v2
-   [x] I have tested my …
> fix: Correctly mark peer-dependencies as external dependencies, disable export of module components

- .storybook/preview.tsx
- CHANGELOG.md
- src/core/components/states/index.ts
- src/core/components/states/statePingAnimation/index.ts
- src/core/components/states/statePingAnimation/statePingAnimation.test.tsx
- src/core/components/states/statePingAnimation/statePingAnimation.tsx
- src/core/components/states/statePingAnimation/statePingAnimations.stories.tsx
- Implements the `StatePingAnimation` core component
Task: [APP-2988](https://aragonassociation.atlassian.net/browse/APP-2988)
-   [ ] I have tested my …
> feat: APP-2988 - Implement StatePingAnimation core component

- CHANGELOG.md
- package.json
- rollup.config.js
- yarn.lock
- With the introduction of wagmi hooks, I saw multiple warnings when building modules components (e.g. circular dependencies). It was because we were only setting the dependencies as externals listed on the package json without including their subfolders (e.g. only `wagmi` and not `wagmi/chains` as well). That's why I'm including a new `peerDepsExternal` plugin during the library build to mark all the dependencies and all eventual subfolders as externals. This is done internally by the plugin by building a regex for each dependency, e.g. /wagmi/,/viem/ and so on.
-   [x] I have commented my code, particularly in …
> chore: Use peer-deps plugin to avoid bundling dependencies and their eventual subfolders

- CHANGELOG.md
- src/core/utils/formatterUtils/formatterUtils.mdx
- src/core/utils/formatterUtils/formatterUtils.test.ts
- src/core/utils/formatterUtils/formatterUtils.ts
- src/core/utils/formatterUtils/formatterUtilsDefinitions.ts
- src/modules/components/asset/assetDataListItem/assetDataListItemStructure/assetDataListItemStructure.tsx
- Update formatter to handle `withSign` option
- Allow every format to be customised
TODO:
- Waiting okay from product 
-   [ ] I have updated the `CHANGELOG.md` file in the root folder of the package after the [UPCOMING] title and before
-   [x] I have tested my code …
> feat: Update formatter to handle negative numbers and withSign option

- CHANGELOG.md
- src/index.ts
- Exports the module components in preparation for a new release
-   [ ] I have tested my code on the test network.
> chore: Export module components

- CHANGELOG.md
- src/modules/components/asset/assetTransfer/assetTransfer.stories.tsx
- src/modules/components/asset/assetTransfer/assetTransfer.test.tsx
- src/modules/components/asset/assetTransfer/assetTransfer.tsx
- src/modules/components/asset/assetTransfer/assetTransferAddress.tsx
- src/modules/components/asset/assetTransfer/assetTransferAddress/assetTransferAddress.test.tsx
- src/modules/components/asset/assetTransfer/assetTransferAddress/assetTransferAddress.tsx
- src/modules/components/asset/assetTransfer/assetTransferAddress/index.ts
- src/modules/components/asset/assetTransfer/index.ts
- src/modules/components/asset/index.ts
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.api.ts
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.tsx
- src/modules/types/compositeAddress.ts
implement AssetTransfer module component with tests and stories
Task: [APP-2977](https://aragonassociation.atlassian.net/browse/APP-2977)
[APP-2977]: …
> feat: APP-2977 - Implement AssetTransfer module component

- CHANGELOG.md
- package.json
- rollup.config.js
- Drop common-js support, current common-js build is broken as viem is ESM-only
> chore: Drop common-js support

- CHANGELOG.md
- src/core/components/link/link.tsx
- src/modules/components/proposal/proposalDataListItem/approvalThresholdResult/approvalThresholdResult.test.tsx
- src/modules/components/proposal/proposalDataListItem/approvalThresholdResult/approvalThresholdResult.tsx
- src/modules/components/proposal/proposalDataListItem/majorityVotingResult/majorityVotingResult.test.tsx
- src/modules/components/proposal/proposalDataListItem/majorityVotingResult/majorityVotingResult.tsx
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStatus/proposalDataListItemStatus.test.tsx
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStatus/proposalDataListItemStatus.tsx
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.api.ts
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.stories.tsx
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.test.tsx
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.tsx
- src/modules/utils/addressUtils/addressUtils.test.tsx
- src/modules/utils/addressUtils/addressUtils.ts
-   Add `stageId` and `stageTitle` properties to `IApprovalThresholdResult` & `IMajorityVotingResult` interfaces
-   Add `id` and optional `tag` properties to `ProposalDataListItemStructure`
-   Remove `publisherProfileLink` and `protocolUpdate` properties from `ProposalDataListItemStructure`
-   Update `date` and `result` properties of `ProposalDataListItemStructure` to be optional and `publisher` to allow for
multiple publishers
-   Fixed `Link` core component children to truncate properly when overflowing
Task: [APP-3094](https://aragonassociation.atlassian.net/browse/APP-3094)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] I have selected the correct …
> feat: APP-3094 - Update ProposalDataListItemStrucure component

- CHANGELOG.md
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.tsx
- fixes the issue of `ProposalDataListItemStructure` title displaying on multiple lines
Task: [APP-3104](https://aragonassociation.atlassian.net/browse/APP-3104)
the latest …
> fix: APP-3104 - Clamp ProposalDataListItemStructure title to single line

- CHANGELOG.md
- src/core/components/accordion/accordionItemHeader/accordionItemHeader.tsx
- updates the styling of the `AccordionItem` `AvatarIcon` when disabled
-   [ ] I have tested my code on the test network.
> fix: update disabled Accordion Item icon stying

- CHANGELOG.md
- src/core/components/accordion/accordionItemHeader/accordionItemHeader.tsx
- src/core/components/avatars/avatar/avatar.tsx
- src/core/components/avatars/avatarIcon/avatarIcon.tsx
- src/core/components/button/button.tsx
- src/core/components/dataList/dataListFilter/dataListFilter.tsx
- src/core/components/icon/icon.tsx
- src/core/components/illustrations/illustrationHuman/illustrationHuman.tsx
- src/core/components/illustrations/illustrationObject/illustrationObject.tsx
- src/core/components/progress/progress.tsx
- src/core/components/spinner/spinner.tsx
- src/core/components/states/stateSkeletonBar/stateSkeletonBar.tsx
- src/core/components/states/stateSkeletonCircular/stateSkeletonCircular.tsx
- src/core/test/svgTransform.js
- src/core/types/responsive.ts
- src/core/utils/responsiveUtils/responsiveUtils.test.ts
- src/core/utils/responsiveUtils/responsiveUtils.ts
- src/modules/components/asset/assetDataListItem/assetDataListItemSkeleton/assetDataListItemSkeleton.tsx
- src/modules/components/dao/daoDataListItem/daoDataListItemSkeleton/daoDataListItemSkeleton.tsx
- src/modules/components/transaction/transactionDataListItem/transactionDataListItemSkeleton/transactionDataListItemSkeleton.tsx
- src/modules/components/transaction/transactionDataListItem/transactionDataListItemStructure/transactionDataListItemStructure.tsx
- src/modules/components/vote/voteDataListItem/voteDataListItemSkeleton/voteDataListItemSkeleton.tsx
- src/modules/index.ts
- Fix responsiveness classes and utilities to support style for screens below sm breakpoint
- Cleanup usage of `shrink-0` class name
-   [x] I have tested my …
> fix: Fix responsiveness classes and utilities to support style for screens below sm breakpoint

- CHANGELOG.md
- src/core/components/button/button.test.tsx
- src/core/components/cards/cardSummary/cardSummary.test.tsx
- src/core/components/collapsible/collapsible.test.tsx
- src/core/components/dataList/dataListFilter/dataListFilter.test.tsx
- src/core/components/dataList/dataListFilter/dataListFilterSort.test.tsx
- src/core/components/dataList/dataListPagination/dataListPagination.test.tsx
- src/core/components/dataList/dataListRoot/dataListRoot.test.tsx
- src/core/components/dialogs/dialog/dialogHeader/dialogHeader.test.tsx
- src/core/components/dialogs/dialogAlert/dialogAlertRoot/dialogAlertRoot.test.tsx
- src/core/components/dropdown/dropdownContainer/dropdownContainer.test.tsx
- src/core/components/input/inputDate/inputDate.test.tsx
- src/core/components/input/inputFileAvatar/inputFileAvatar.test.tsx
- src/core/components/input/inputNumber/inputNumber.test.tsx
- src/core/components/input/inputNumberMax/inputNumberMax.test.tsx
- src/core/components/input/inputSearch/inputSearch.test.tsx
- src/core/components/input/inputTime/inputTime.test.tsx
- src/core/components/link/link/link.test.tsx
- src/core/components/radioGroup/radio/radio.test.tsx
- src/core/components/radioGroup/radioCard/radioCard.test.tsx
- src/core/components/radioGroup/radioGroup/radioGroup.test.tsx
- src/core/components/switch/switch.test.tsx
- src/core/components/textAreas/textAreaRichText/textAreaRichText.test.tsx
- src/core/components/textAreas/textAreaRichText/textAreaRichTextActions.test.tsx
- src/core/components/toggles/toggle/toggle.test.tsx
- src/core/components/toggles/toggleGroup/toggleGroup.test.tsx
- src/core/components/tooltip/tooltip.test.tsx
- src/modules/components/address/addressInput/addressInput.test.tsx
Migrate to using userEvent instead of fireEvent for unit tests. The only test case which still relies on fireEvent is "calls the onChange property on input change."
Task: [APP-2855](https://aragonassociation.atlassian.net/browse/APP-2855)
-   [ ] I have updated the `CHANGELOG.md` file in the root folder of the package after the [UPCOMING] title and before …
> feat(APP-2855): Migrate to userEvent from fireEvent

- CHANGELOG.md
- src/core/utils/index.ts
- src/core/utils/ssrUtils/index.ts
- src/core/utils/ssrUtils/ssrUtils.client.test.ts
- src/core/utils/ssrUtils/ssrUtils.server.test.ts
- src/core/utils/ssrUtils/ssrUtils.ts
- src/modules/components/member/memberAvatar/memberAvatar.test.tsx
- src/modules/components/member/memberAvatar/memberAvatar.tsx
- src/modules/components/member/memberDataListItem/memberDataListItemStructure/memberDataListItemStructure.stories.tsx
- src/modules/components/member/memberDataListItem/memberDataListItemStructure/memberDataListItemStructure.test.tsx
- src/modules/components/member/memberDataListItem/memberDataListItemStructure/memberDataListItemStructure.tsx
- Update MemberAvatar component to only call the blockies.create utility on client side
- Implement ssr-utils to check current environment
- Update MemberDataListItem component to accept votingpower set as string
Task: [APP-3202](https://aragonassociation.atlassian.net/browse/APP-3202)
-   [x] I …
> fix(APP-3202): Ensure MemberAvatar component works on server environments

- CHANGELOG.md
- src/core/components/accordion/accordionItemContent/accordionItemContent.tsx
- src/core/components/accordion/accordionItemHeader/accordionItemHeader.tsx
- src/core/components/dropdown/dropdownContainer/dropdownContainer.tsx
- src/core/components/dropdown/dropdownItem/dropdownItem.tsx
- src/core/components/forms/checkbox/checkbox.tsx
- src/core/components/forms/checkboxCard/checkboxCard.tsx
- src/core/components/forms/radioGroup/radio/radio.tsx
- src/core/components/forms/radioGroup/radioCard/radioCard.tsx
- src/core/components/forms/radioGroup/radioGroup/radioGroup.tsx
- src/core/components/tabs/tabsContent/tabsContent.tsx
- src/core/components/tabs/tabsList/tabsList.tsx
- src/core/components/tabs/tabsRoot/tabsRoot.tsx
- src/core/components/tabs/tabsTrigger/tabsTrigger.tsx
- src/core/components/tooltip/tooltip.tsx
Remove Radix props dependency.
Task: [APP-2885](https://aragonassociation.atlassian.net/browse/APP-2885)
-   [X] New feature (non-breaking change which adds functionality)
-   [X] I have selected the correct base branch.
-   [X] I have performed a self-review of my own code.
-   [X] I have commented my code, particularly in hard-to-understand areas.
-   [X] I have made corresponding changes to the documentation.
-   [X] My changes generate no new warnings.
-   [X] Any dependent changes have been merged and published in downstream modules.
-   [X] I ran all tests with success and extended them if necessary.
-   [X] I have …
> feat(APP-2885): Remove Radix props dependency

- .storybook/main.ts
- CHANGELOG.md
Revert to using `react-docgen-typescript` to generate args description from prop comments.
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] I have updated the …
> fix: Revert to using react-docgen-typescript for higher docs fidelity 

- CHANGELOG.md
- src/core/utils/formatterUtils/index.ts
- src/modules/components/address/addressInput/addressInput.tsx
- src/modules/components/asset/assetTransfer/assetTransfer.tsx
- src/modules/hooks/useBlockExplorer/index.ts
- src/modules/hooks/useBlockExplorer/useBlockExplorer.test.ts
- src/modules/hooks/useBlockExplorer/useBlockExplorer.ts
Make params for useBlockExplorer hook optional to handle DAO query requirements
use enum for more secure type enforcement of link "types" in construction
export DateFormat and other usages for DateFormatter util
-   [x] I have updated the `CHANGELOG.md` file in the root folder of the package after …
> fix: update required params for useBlockExplorer hook, exports types for formatting dates

- CHANGELOG.md
- src/core/utils/formatterUtils/formatterUtils.test.ts
- src/core/utils/formatterUtils/formatterUtils.ts
- src/modules/components/odsModulesProvider/odsModulesProvider.mdx
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStatus/proposalDataListItemStatus.test.tsx
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStatus/proposalDataListItemStatus.tsx
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.api.ts
- Fix `ProposalDataListItem` component to avoid showing `null ago` when date is not defined;
- Fix DURATION date format to use the locale defined on the formatter utils
the latest …
> fix: Fix undefined date case on ProposalDataListItem module component, fix DURATION date format

- CHANGELOG.md
- src/modules/components/vote/index.ts
- src/modules/hooks/useBlockExplorer/useBlockExplorer.test.ts
- src/modules/hooks/useBlockExplorer/useBlockExplorer.ts
- Export `VoteIndicator` type
- Update `useBlockExplorer` hook to export a `getBlockExplorer` function and update `buildEntityUrl` function to support a `chainId` parameter overriding the `chainId` parameter set on the hook.
Task: [APP-3460](https://aragonassociation.atlassian.net/browse/APP-3460) …
> feat(APP-3460): Export VoteIndicator type, update buildEntityUrl function to support a chainId parameter

- CHANGELOG.md
- src/modules/components/proposal/proposalVoting/proposalVotingBreakdownToken/proposalVotingBreakdownToken.test.tsx
- src/modules/components/proposal/proposalVoting/proposalVotingBreakdownToken/proposalVotingBreakdownToken.tsx
- Hide minParticipation details from token-voting breakdown when property is set to zero
Task: [APP-3461](https://aragonassociation.atlassian.net/browse/APP-3461)
the latest …
> fix(APP-3461): Hide minParticipation details from token-voting breakdown when property is set to zero

- CHANGELOG.md
- src/modules/components/proposal/proposalActions/proposalActions/proposalActions.tsx
- src/modules/components/proposal/proposalActions/proposalActionsAction/proposalActionsAction.test.tsx
- src/modules/components/proposal/proposalActions/proposalActionsAction/proposalActionsAction.tsx
- src/modules/components/proposal/proposalActions/proposalActionsUtils.test.tsx
- src/modules/components/proposal/proposalActions/proposalActionsUtils.ts
- Correctly forward web3 parameters to native ProposalActions components
Task: [APP-3495](https://aragonassociation.atlassian.net/browse/APP-3495)
-   [x] I …
> fix(APP-3495): Correctly forward web3 parameters to native ProposalActions components

- .github/dependabot.yml
- CHANGELOG.md
- package.json
- src/core/components/dropdown/dropdownItem/dropdownItem.stories.tsx
- src/core/components/forms/hooks/useNumberMask.ts
- src/core/components/forms/inputNumber/inputNumber.test.tsx
- src/core/components/forms/inputNumber/inputNumber.tsx
- src/core/components/forms/inputNumberMax/inputNumberMax.test.tsx
- src/core/components/forms/inputNumberMax/inputNumberMax.tsx
- yarn.lock
- From version `7.6.0`, the `react-imask` does not correctly trigger the `onAccept` callback on value change, see issue here => https://github.com/uNmAnNeR/imaskjs/pull/1045
Task: [APP-3440](https://aragonassociation.atlassian.net/browse/APP-3440)
-   [x] I have updated the `CHANGELOG.md` file in …
> fix(APP-3440): Fix NumberInput component to correctly update value on buttons click

- .storybook/manager.ts
- .storybook/preview.tsx
- .storybook/theme.ts
- CHANGELOG.md
Update logo, and storybook branding in preparation 
Task: [APP-3507](https://aragonassociation.atlassian.net/browse/APP-3507) …
> feat(APP-3507): Add aragon theming to storybook

- CHANGELOG.md
- src/modules/components/asset/assetDataListItem/assetDataListItemStructure/assetDataListItemStructure.test.tsx
- src/modules/components/asset/assetDataListItem/assetDataListItemStructure/assetDataListItemStructure.tsx
Using the wrong format for percentages. Wasn't noticed until we fixed issue APP-3417.
Task: Related to APP-3417 …
> fix: Use correct percentage format on AssetDataListItemStructure module component

- CHANGELOG.md
- src/core/components/forms/textAreaRichText/textAreaRichText.test.tsx
- src/core/components/forms/textAreaRichText/textAreaRichText.tsx
- src/core/test/setup.ts
- src/core/test/utils/createRangeMock.ts
- src/core/test/utils/index.ts
- Expose empty string instead of empty paragraph (`<p></p>`) as default value on TextAreaRichText component
Task: [APP-3308](https://aragonassociation.atlassian.net/browse/APP-3308)
-   [x] I have updated the `CHANGELOG.md` file in the root folder of the package after the [UPCOMING] title and …
> fix(APP-3308): Fix TextAreaRichText component to expose empty string as default value

- CHANGELOG.md
- src/modules/components/proposal/proposalActions/actions/proposalActionChangeMembers/proposalActionChangeMembers.test.tsx
- src/modules/components/proposal/proposalActions/actions/proposalActionChangeMembers/proposalActionChangeMembers.tsx
- src/modules/components/proposal/proposalActions/actions/proposalActionChangeSettings/proposalActionChangeSettings.test.tsx
- src/modules/components/proposal/proposalActions/actions/proposalActionChangeSettings/proposalActionChangeSettings.tsx
- src/modules/components/proposal/proposalActions/actions/proposalActionTokenMint/proposalActionTokenMint.stories.tsx
- src/modules/components/proposal/proposalActions/actions/proposalActionTokenMint/proposalActionTokenMint.test.tsx
- src/modules/components/proposal/proposalActions/actions/proposalActionUpdateMetadata/proposalActionUpdateMetadata.test.tsx
- src/modules/components/proposal/proposalActions/actions/proposalActionWithdrawToken/proposalActionWithdrawToken.stories.tsx
- src/modules/components/proposal/proposalActions/actions/proposalActionWithdrawToken/proposalActionWithdrawToken.test.tsx
- src/modules/components/proposal/proposalActions/proposalActions/proposalActions.api.ts
- src/modules/components/proposal/proposalActions/proposalActions/proposalActions.tsx
- src/modules/components/proposal/proposalActions/proposalActionsAction/proposalActionsAction.test.tsx
- src/modules/components/proposal/proposalActions/proposalActionsAction/proposalActionsAction.tsx
- src/modules/components/proposal/proposalActions/proposalActionsTypes/proposalActionComponent.ts
The `useFieldArray` hook from `react-hook-form` requires us to set a specific `key` when using the ProposalActions component as form field (see https://react-hook-form.com/docs/usefieldarray). We also need to access the form-fields on the actions through the current action index inside the array (e.g. `useFormField('actions.[${index}]')`).
Usage example on app-next PR: https://github.com/aragon/app-next/pull/137/files
As we're forwarding more and more properties from the parent component to the `ProposalActionsAction` component, I believe we should revisit the implementation to split it into two components. Also passing a property like `actionKey` to simply set a key on a React component isn't very clean, but it's a quick implementation for now. I opened a ticket here with some details: …
> feat(APP-3614): Update ProposalActions component to support actionKey property and forward index property

- CHANGELOG.md
- src/core/components/avatars/avatar/avatar.tsx
- src/modules/components/vote/voteProposalDataListItem/voteProposalDataListItemStructure/voteProposalDataListItemStructure.stories.tsx
- src/modules/components/vote/voteProposalDataListItem/voteProposalDataListItemStructure/voteProposalDataListItemStructure.test.tsx
- src/modules/components/vote/voteProposalDataListItem/voteProposalDataListItemStructure/voteProposalDataListItemStructure.tsx
- Add custom label for  `VoteProposalDataListItem` component.
- - Add new `xs` size for core `Avatar` component
Task: [APP-3490](https://aragonassociation.atlassian.net/browse/APP-3490)
-   [x] I …
> feat(APP-3490): Add custom label property for VoteProposalDataListItem component

- CHANGELOG.md
- src/core/components/accordion/accordionContainer/accordionContainer.stories.tsx
- src/core/components/accordion/accordionItemContent/accordionItemContent.tsx
- src/core/components/tabs/tabsRoot/tabsRoot.stories.tsx
- src/core/components/tabs/tabsTrigger/tabsTrigger.stories.tsx
- src/core/components/tabs/tabsTrigger/tabsTrigger.test.tsx
- src/core/components/tabs/tabsTrigger/tabsTrigger.tsx
- src/modules/components/proposal/proposalActions/proposalActionsAction/proposalActionsActionRawView/index.ts
- src/modules/components/proposal/proposalVoting/proposalVotingStage/proposalVotingStage.tsx
- src/modules/components/proposal/proposalVoting/proposalVotingTabs/proposalVotingTabs.test.tsx
- src/modules/components/proposal/proposalVoting/proposalVotingTabs/proposalVotingTabs.tsx
- src/modules/components/vote/index.ts
- Update `<ProposalVotingTabs />` module component to disable `Breakdown` and `Votes` tabs when voting status is not
active
- Update `Tabs` core component to handle disabled tab trigger state
- Fix type exports
Task: [APP-3668](https://aragonassociation.atlassian.net/browse/APP-3668)
- …
> feat(APP-3668): Update ProposalVotingTabs component to disable Breakdown / Votes tabs when status is not active

- CHANGELOG.md
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.api.ts
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.stories.tsx
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.test.tsx
- src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.tsx
- Set proposal type optional on ProposalDataListItem component to make it more flexible and support custom governance plugins.
Task: [APP-3676](https://aragonassociation.atlassian.net/browse/APP-3676)
-   [x] I have updated the `CHANGELOG.md` file in the root folder of the package after …
> feat(APP-3676): Update ProposalDataListItem component to make proposal type optional

- CHANGELOG.md
- src/core/components/breadcrumbs/breadcrumbs.stories.tsx
- src/core/components/breadcrumbs/breadcrumbs.tsx
- src/core/components/definitionList/definitionListItem/definitionListItem.stories.tsx
- src/core/components/definitionList/definitionListItem/definitionListItem.tsx
- Update DefinitionListItem and Breadcrumbs components to truncate long strings
> fix: Update DefinitionListItem and Breadcrumbs components to truncate long strings

- CHANGELOG.md
- src/core/components/forms/hooks/useNumberMask.test.ts
- src/core/components/forms/hooks/useNumberMask.ts
- src/core/components/forms/inputNumber/inputNumber.stories.tsx
- src/core/components/forms/inputNumber/inputNumber.test.tsx
- src/core/components/forms/inputNumber/inputNumber.tsx
- Fix InputNumber component, update tests and stories
> fix: Fix InputNumber component to trigger onChange callback on + / - button click

- .github/workflows/library-publish.yml
- .github/workflows/storybook-preview-deploy.yml
- CHANGELOG.md
- src/core/components/gukCoreProvider/gukCoreProvider.tsx
Should remove tagging issue preventing latest on package publish flow. A couple more ODS usages removed. 
> fix(APP-3714): Rename default core context values to use "guk" prefix

- CHANGELOG.md
- src/modules/components/proposal/proposalVoting/proposalVoting.stories.tsx
- src/modules/components/proposal/proposalVoting/proposalVotingContainer/proposalVotingContainer.test.tsx
- src/modules/components/proposal/proposalVoting/proposalVotingContainer/proposalVotingContainer.tsx
- src/modules/components/proposal/proposalVoting/proposalVotingStage/proposalVotingStage.test.tsx
- src/modules/components/proposal/proposalVoting/proposalVotingStage/proposalVotingStage.tsx
- The radix-ui accordion does not update the active item when changing the `defaultValue` property. In order to mark the next stage active as soon as the previous stage is advanced, we need to control the accordion value by using the `value` and `onValueChange` accordion properties. Same changes are needed for the `ProposalVotingStage` component to properly update the default voting-tab when a stage status changes from PENDING to ACTIVE
Task: [APP-3626](https://aragonassociation.atlassian.net/browse/APP-3626)
-   [x] I have made corresponding changes to …
> fix(APP-3626): Update ProposalVoting Container/Stage components to correctly update on stage and status changes

- .github/workflows/library-publish.yml
- CHANGELOG.md
- Fix publish library workflow to mark as `latest` the latest library version
> fix: Fix publish library workflow to mark the latest library version as "latest"

- CHANGELOG.md
- src/core/components/dialogs/dialog/dialogFooter/dialogFooter.tsx
- Support `type` property on the buttons of the `<Dialog.Footer />` core component
Task: [APP-3309](https://aragonassociation.atlassian.net/browse/APP-3309)
[APP-3309]: https://aragonassociation.atlassian.net/browse/APP-3309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(APP-3309): Support type property on the buttons of the DialogFooter core component

- CHANGELOG.md
- src/modules/components/proposal/proposalActions/proposalActionsItem/proposalActionsItem.stories.tsx
- src/modules/components/proposal/proposalActions/proposalActionsItem/proposalActionsItem.test.tsx
- src/modules/components/proposal/proposalActions/proposalActionsItem/proposalActionsItem.tsx
- Fix warning feedback on ProposalAction component, disable decoded view for actions with no parameters
Task: [APP-3806](https://aragonassociation.atlassian.net/browse/APP-3806)
[APP-3806]: https://aragonassociation.atlassian.net/browse/APP-3806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(APP-3806): Fix warning feedback on ProposalAction component, disable decoded view for actions with no parameters

- CHANGELOG.md
- src/modules/components/asset/assetTransfer/assetTransfer.stories.tsx
- src/modules/components/asset/assetTransfer/assetTransfer.test.tsx
- src/modules/components/asset/assetTransfer/assetTransfer.tsx
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionChangeMembers/proposalActionChangeMembers.test.tsx
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionChangeMembers/proposalActionChangeMembers.tsx
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionTokenMint/proposalActionTokenMint.api.ts
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionTokenMint/proposalActionTokenMint.test.tsx
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionTokenMint/proposalActionTokenMint.tsx
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionWithdrawToken/proposalActionWithdrawToken.api.tsx
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionWithdrawToken/proposalActionWithdrawToken.stories.tsx
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionWithdrawToken/proposalActionWithdrawToken.test.tsx
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionWithdrawToken/proposalActionWithdrawToken.testUtils.ts
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionWithdrawToken/proposalActionWithdrawToken.tsx
- Updated `hash` property to be optional on the `AssetTransfer` module component
- Added link to the block explorer for members on the `ProposalActionChangeMembers` module component
- Added receiver block explorer link to the `ProposalActionTokenMint` module component
Task: [APP-3556](https://aragonassociation.atlassian.net/browse/APP-3556)
Task: [APP-3830](https://aragonassociation.atlassian.net/browse/APP-3830)
Task: [APP-3430](https://aragonassociation.atlassian.net/browse/APP-3430)
[APP-3556]: https://aragonassociation.atlassian.net/browse/APP-3556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-3830]: https://aragonassociation.atlassian.net/browse/APP-3830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
> fix(APP-3556): Add correct block explorer links to actions

- .github/workflows/storybook-publish.yml
Please include a summary of the change and be sure you follow the contributions rules we do provide
[here](./CONTRIBUTIONS.md)
Task: [APP-0000](https://aragonassociation.atlassian.net/browse/APP-0000)
> updated new storybook workflow

- CHANGELOG.md
- src/core/components/forms/inputFileAvatar/index.tsx
- src/core/components/forms/inputFileAvatar/inputFileAvatar.api.ts
- src/core/components/forms/inputFileAvatar/inputFileAvatar.stories.tsx
- src/core/components/forms/inputFileAvatar/inputFileAvatar.test.tsx
- src/core/components/forms/inputFileAvatar/inputFileAvatar.tsx
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionUpdateMetadata/proposalActionUpdateMetadata.api.ts
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionUpdateMetadata/proposalActionUpdateMetadata.stories.tsx
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionUpdateMetadata/proposalActionUpdateMetadata.test.tsx
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionUpdateMetadata/proposalActionUpdateMetadata.testUtils.ts
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionUpdateMetadata/proposalActionUpdateMetadata.tsx
Update InputFileAvatar component to handle initial preview and add onCancel callback
Update IProposalActionUpdateMetadataDaoMetadata logo property to avatar
Task: [APP-3693](https://aragonassociation.atlassian.net/browse/APP-3693)
[APP-3693]: https://aragonassociation.atlassian.net/browse/APP-3693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(APP-3693): Update InputFileAvatar component to handle initial preview and add onCancel callback

- CHANGELOG.md
- src/core/components/forms/textArea/textArea.tsx
- src/modules/components/address/addressInput/addressInput.tsx
Adds min-h-11 to address input which keeps interior height of text-area from mounting with style:"height: 0" by default when composed in forms and other components
Task: [APP-3851](https://aragonassociation.atlassian.net/browse/APP-3851)
[APP-3851]: https://aragonassociation.atlassian.net/browse/APP-3851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(APP-3851): Prevent displacement of placeholder on AddressInput

- .github/pull_request_template.md
- CHANGELOG.md
- Update the pull-request template
> chore: Update pull-request template

- CHANGELOG.md
- src/core/components/alerts/alertCard/alertCard.tsx
- src/core/components/alerts/alertInline/alertInline.test.tsx
- src/core/components/alerts/alertInline/alertInline.tsx
- src/core/components/avatars/avatarIcon/avatarIcon.test.tsx
- src/core/components/button/button.test.tsx
- src/core/components/cards/cardSummary/cardSummary.test.tsx
- src/core/components/cards/cardSummary/cardSummary.tsx
- src/modules/components/transaction/transactionDataListItem/transactionDataListItemStructure/transactionDataListItemStructure.test.tsx
- src/modules/components/transaction/transactionDataListItem/transactionDataListItemStructure/transactionDataListItemStructure.tsx
- src/modules/components/wallet/wallet.tsx
- src/modules/hooks/useBlockExplorer/index.ts
- src/modules/hooks/useBlockExplorer/useBlockExplorer.api.ts
- src/modules/hooks/useBlockExplorer/useBlockExplorer.test.ts
- src/modules/hooks/useBlockExplorer/useBlockExplorer.ts
- src/modules/utils/addressUtils/addressUtils.test.tsx
- Improve code coverage on core and modules components
> chore: Add missing tests on core and module components

- CHANGELOG.md
- src/modules/assets/copy/modulesCopy.ts
- src/modules/components/proposal/proposalActions/proposalActionsItem/proposalActionsItem.test.tsx
- src/modules/components/proposal/proposalActions/proposalActionsItem/proposalActionsItem.tsx
Uses the config for supported chains to fetch correct token symbol when warning users about native transfers in a proposal action. 
Task: [APP-3882](https://aragonassociation.atlassian.net/browse/APP-3882)
[APP-3882]: https://aragonassociation.atlassian.net/browse/APP-3882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(APP-3882): Use correct native token symbol for asset transfer warning

- CHANGELOG.md
- src/core/components/tabs/tabsList/tabsList.test.tsx
- src/core/components/tabs/tabsList/tabsList.tsx
- src/core/components/tabs/tabsRoot/tabsRoot.stories.tsx
- src/core/components/tabs/tabsTrigger/tabsTrigger.test.tsx
Update Tab component to not render the TabList when there is a single child
Task: [APP-3954](https://aragonassociation.atlassian.net/browse/APP-3954)
[APP-3954]: https://aragonassociation.atlassian.net/browse/APP-3954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(APP-3954): Update Tab component to not render the TabList when there is a single child

- CHANGELOG.md
- src/core/components/forms/hooks/useNumberMask.test.ts
- src/core/components/forms/hooks/useNumberMask.ts
Fix `InputNumber` component so that it properly handles decimals when there is a default values set
Task: [APP-3978](https://aragonassociation.atlassian.net/browse/APP-3978)
[APP-3978]: https://aragonassociation.atlassian.net/browse/APP-3978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(APP-3978): Fix InputNumber component so that it properly handles decimals when there is a default values set

- CHANGELOG.md
- src/core/components/forms/inputFileAvatar/inputFileAvatar.tsx
- Set cancel button type to "button" to avoid form submit event
Task: [APP-3977](https://aragonassociation.atlassian.net/browse/APP-3977)
[APP-3977]: https://aragonassociation.atlassian.net/browse/APP-3977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(APP-3977): Fix cancel button type of InputFileAvatar component

- .yarnrc.yml
- CHANGELOG.md
- Disable `postinstall` scripts by default
> chore: Disable postinstall scripts by default

- CHANGELOG.md
- src/theme/tokens/primitives/typography.css
Update `font-weight-normal` to 400 to reflect the style definitions in [Manrope Font](https://fonts.google.com/specimen/Manrope).
Task: [APP-4029](https://aragonassociation.atlassian.net/browse/APP-4029)
[APP-4029]: https://aragonassociation.atlassian.net/browse/APP-4029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(APP-4029): Update font-weight-normal to 400

- CHANGELOG.md
- src/core/components/avatars/avatar/avatar.tsx
- src/core/components/toggles/toggleGroup/toggleGroup.stories.tsx
- src/core/components/toggles/toggleGroup/toggleGroup.tsx
- src/modules/components/dao/daoAvatar/daoAvatar.tsx
- Add `variant` property to `ToggleGroup` component to support "space-between" spacing
- Add XS size to Avatar core component
Task: [APP-3652](https://aragonassociation.atlassian.net/browse/APP-3652)
[APP-3652]: https://aragonassociation.atlassian.net/browse/APP-3652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(APP-3652): Add variant property to ToggleGroup component, support XS size on Avatar component

- CHANGELOG.md
- src/modules/components/proposal/proposalVoting/proposalVotingBreakdownToken/proposalVotingBreakdownToken.test.tsx
- src/modules/components/proposal/proposalVoting/proposalVotingBreakdownToken/proposalVotingBreakdownToken.tsx
Breakdown now correctly calculates and outputs support based on `Yes / (Yes + No)`
Task: [APP-4115](https://aragonassociation.atlassian.net/browse/APP-4115)
[APP-4115]: https://aragonassociation.atlassian.net/browse/APP-4115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(APP-4115): Update 'support' logic for correct calc on ProposalVotingBreakdownToken

- .changeset/silver-melons-show.md
- CHANGELOG.md
- src/core/components/dataList/dataListPagination/dataListPagination.stories.tsx
- src/core/components/dataList/dataListPagination/dataListPagination.tsx
Update pagination component to apply different variant to the progress bar when there are no more items to show
Task: [APP-4044](https://aragonassociation.atlassian.net/browse/APP-4044)
[APP-4044]: https://aragonassociation.atlassian.net/browse/APP-4044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(APP-4044): Update pagination component to apply different variant to the progress bar when there are no more items to show

- .changeset/good-badgers-visit.md
- src/core/components/dialogs/dialog/dialogRoot/dialogRoot.tsx
- Remove outline from dialog to prevent unwanted styling when focus is applied
Worth noting that there are some accessibility considerations here.
Task: [APP-3610](https://aragonassociation.atlassian.net/browse/APP-3610)
[APP-3610]: https://aragonassociation.atlassian.net/browse/APP-3610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(APP-3610): Remove outline from dialog to prevent unwanted styling when focus is applied

- .changeset/sharp-carrots-search.md
- src/core/components/dropdown/dropdownItem/dropdownItem.tsx
Prevent default onClick/onSelect behaviour for Dropdown items when disabled.
Task: [APP-3488](https://aragonassociation.atlassian.net/browse/APP-3488)
[APP-3488]: https://aragonassociation.atlassian.net/browse/APP-3488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(APP-3488): Prevent default onClick/onSelect behaviour for Dropdown items when disabled

- .changeset/loud-garlics-wear.md
- src/core/components/definitionList/definitionListItem/definitionListItem.stories.tsx
- src/core/components/definitionList/definitionListItem/definitionListItem.test.tsx
- src/core/components/definitionList/definitionListItem/definitionListItem.tsx
- src/modules/assets/copy/modulesCopy.ts
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionChangeSettings/index.ts
- src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionChangeSettings/proposalActionChangeSettings.api.tsx
- src/modules/components/proposal/proposalVoting/proposalVotingDetails/proposalVotingDetails.test.tsx
- src/modules/components/proposal/proposalVoting/proposalVotingDetails/proposalVotingDetails.tsx
- src/modules/types/definitionSetting.ts
- src/modules/types/index.ts
Implement 'link' prop and component within `<DefinitionList.Item />`
Task: [APP-4205](https://aragonassociation.atlassian.net/browse/APP-4205)
[APP-4205]: https://aragonassociation.atlassian.net/browse/APP-4205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(APP-4205): Implement 'link' prop and component within DefinitionListItem

- .changeset/warm-plants-talk.md
- src/core/components/documentParser/documentParser.tsx
- Expose the `immediatelyRender` property on the `DocumentParser` component for SSR usage as already done on the `TextAreaRichText` component
> feat: Update DocumentParser core component to expose immediatelyRender prop

- .changeset/big-texts-hurt.md
- src/core/components/forms/checkboxCard/checkboxCard.tsx
- src/core/components/forms/radioCard/radioCard.tsx
We've always struggled in the governance designer to have enough space to add descriptions to components. Giving a little more space will help. Selim approved the design change and will do in figma.
> fix: Reduce text size of the descriptions on the RadioCard and CheckboxCard components

- .changeset/nine-moles-start.md
- src/modules/components/transaction/transactionDataListItem/transactionDataListItemStructure/transactionDataListItemStructure.api.ts
- src/modules/components/transaction/transactionDataListItem/transactionDataListItemStructure/transactionDataListItemStructure.stories.tsx
- src/modules/components/transaction/transactionDataListItem/transactionDataListItemStructure/transactionDataListItemStructure.test.tsx
- src/modules/components/transaction/transactionDataListItem/transactionDataListItemStructure/transactionDataListItemStructure.tsx
Add `hideValue` prop to `TransactionDataListItem` to hide the fiat value.
Task: [APP-4534](https://aragonassociation.atlassian.net/browse/APP-4534)
[APP-4534]: https://aragonassociation.atlassian.net/browse/APP-4534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add hideValue flag to TransactionDataListItem

- .changeset/config.json
Reduce the scope of changeset to src folder to avoid adding empty changeset when updating dependencies or other chore updates.
> chore: Reduce the scope of changeset to src folder

- .changeset/honest-mirrors-win.md
- src/core/components/documentParser/documentParser.test.tsx
- src/core/components/documentParser/documentParser.tsx
- src/core/components/forms/textAreaRichText/textAreaRichText.test.tsx
- src/core/components/forms/textAreaRichText/textAreaRichText.tsx
- Fix TextAreaRichText and DocumentParser components after tiptap migration
> fix: Fix TextAreaRichText and DocumentParser components after tiptap migration
