aragon/gov-ui-kit

.github/workflows/library-test.yml, .github/workflows/storybook-preview-deploy.yml, .github/workflows/storybook-preview-remove.yml, CHANGELOG.md
Add preview workflows and enforce update to changelog file
=> Add preview workflows, enforce changelog update

CHANGELOG.md, src/components/listItem/address.tsx
@Fabricevladimir FYI I'm applying your changes to the address-list-item component here
Task: [APP-2319](https://aragonassociation.atlassian.net/browse/APP-2319)
-   [x] I have updated the `CHANGELOG.md` file in the root folder of the package after the [UPCOMING] title and before the latest …
=> feat(APP-2319): Allow ENS address on address list-item component

CHANGELOG.md, README.md, package.json, rollup.config.js, yarn.lock
Set all dependencies as external to avoid bundling duplicate dependencies
=> fix: Set all dependencies as external

CHANGELOG.md, src/components/input/numberInput.tsx, src/components/input/walletInput.tsx
- fixes the padding issue for `input-wallet` and `input-number` components
=> fix: input-wallet and input-number padding

.github/workflows/storybook-preview-deploy.yml, CHANGELOG.md
- Correctly update preview comment on PRs
=> fix: correctly edit preview comments on PRs

.github/workflows/library-test.yml, CHANGELOG.md, src/components/input/valueInput.tsx, src/components/input/walletInputLegacy.tsx
Fix `Unknown event handler property onAdornmentClick. It will be ignored.` warning on `ValueInput` and `WalletInputLegacy` components.
-   [x] I have tested my …
=> fix: unhandled event warning on ValueInput and WalletInputLegacy components

CHANGELOG.md, src/components/input/inputImageSingle.stories.tsx, src/components/input/inputImageSingle.tsx
- added acceptableFileFormat as prop to inputImage component
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] I have updated the `CHANGELOG.md` file in the root folder of the package after the [UPCOMING] title and before the latest …
=> added acceptableFileFormat prop to inputImage

CHANGELOG.md, src/components/backdrop/backdrop.tsx, src/components/modal/modal.stories.tsx, src/components/modal/modal.tsx
revert - fix(APP-2253): Remove scroll from modals and bottom sheet components
Task: [APP-2384](https://aragonassociation.atlassian.net/browse/APP-2384)
-   [x] …
=> revert - fix(APP-2253): Remove scroll from modals and bottom sheet components

CHANGELOG.md, src/utils/addresses.test.ts, src/utils/addresses.tsx
- Update the regex used for the `isEnsDomain` utility to improve its performance
- Add tests for `isEnsDomain` utility …
=> fix: Fix performances of isEnsDomain utility

CHANGELOG.md, src/components/cards/cardProposal.stories.tsx, src/components/cards/cardProposal.tsx
Needed to develop `CardBanner` for `ProposalCard` in order to be able to mark `verified aragon updates` according to design.
Task: [APP-2452](https://aragonassociation.atlassian.net/browse/APP-2452)
-   [ ] I have updated the `CHANGELOG.md` file in the root folder of the package after the …
=> feat: APP-2452 Implemented banner on Proposal Card component

CHANGELOG.md, src/components/pagination/pagination.tsx
=> Feature: Added mobile pagination

CHANGELOG.md, src/components/dropdown/dropdown.tsx, src/components/headers/headerDao.tsx
- updated styling for `HeaderDao` Dao Credentials dropdown items 
- updated `Dropdown` component styling when `focus` and `hover` states are both active
Task: [APP-2462](https://aragonassociation.atlassian.net/browse/APP-2462)
- …
=> Fix: Header DAO dropdown

CHANGELOG.md, package.json, src/styles/index.css
- Fix directory of types declarations
- Remove empty index.css file
Task: [APP-2596](https://aragonassociation.atlassian.net/browse/APP-2596)
-   [x] I have …
=> fix: APP-2596 - Fix directory of types declarations

CHANGELOG.md, rollup.config.js
Task: [APP-2596](https://aragonassociation.atlassian.net/browse/APP-2596)
[APP-2596]: …
=> fix: APP-2596: Fix library build

.github/ISSUE_TEMPLATE/bug_report.md, .github/pull_request_template.md, CHANGELOG.md, README.md, code-of-conduct.md, docs/installation.mdx, prettier.config.js, src/styles/index.mdx, src/utils/formatterUtils/formatterUtils.mdx
- Update prettier configs to correctly format md and mdx files
Task: [APP-2619](https://aragonassociation.atlassian.net/browse/APP-2619)
-   [x] I have …
=> feat: APP-2619 - Update prettier configs to correctly format md files

CHANGELOG.md, src/components/input/index.ts, src/components/input/inputContainer/inputContainer.tsx, src/components/input/inputSearch/index.ts, src/components/input/inputSearch/inputSearch.stories.tsx, src/components/input/inputSearch/inputSearch.test.tsx, src/components/input/inputSearch/inputSearch.tsx, src/components/input/useInputProps.test.ts, src/components/input/useInputProps.ts, tailwind.config.js
- Implement `InputSearch` component
- Fix handling of value length for controlled inputs
Task: [APP-2619](https://aragonassociation.atlassian.net/browse/APP-2619)
the …
=> feat: APP-2619 - Implement InputSearch component

CHANGELOG.md, src/components/avatars/avatarIcon/avatarIcon.tsx, src/components/button/button.api.ts, src/components/button/button.stories.tsx, src/components/button/button.tsx, src/components/icon/icon.tsx, src/components/spinner/spinner.stories.tsx, src/components/spinner/spinner.tsx, src/types/responsive.ts, src/utils/responsiveUtils/responsiveUtils.test.ts, src/utils/responsiveUtils/responsiveUtils.ts
- Update Spinner and Button components to handle responsive sizes
- Update Icon and AvatarIcon components to handle xl and 2xl responsive sizes
-   [x] …
=> feat: Update Spinner and Button components to handle responsive sizes

CHANGELOG.md, src/components/cards/card/card.stories.tsx, src/components/cards/card/card.test.tsx, src/components/cards/card/card.tsx, src/components/cards/card/index.ts, src/components/cards/cardSummary/cardSummary.api.ts, src/components/cards/cardSummary/cardSummary.stories.tsx, src/components/cards/cardSummary/cardSummary.test.tsx, src/components/cards/cardSummary/cardSummary.tsx, src/components/cards/cardSummary/index.ts, src/components/cards/index.ts, src/components/index.ts
- Implement `Card` and `CardSummary` components
Task: [APP-2619](https://aragonassociation.atlassian.net/browse/APP-2619)
-   [x] I have tested my code …
=> feat: APP-2619 - Implement Card and CardSummary components

CHANGELOG.md, jest.config.js, package.json, src/components/input/index.ts, src/components/input/inputContainer/inputContainer.tsx, src/components/input/inputDate/index.ts, src/components/input/inputDate/inputDate.stories.tsx, src/components/input/inputDate/inputDate.test.tsx, src/components/input/inputDate/inputDate.tsx, src/components/input/inputSearch/inputSearch.stories.tsx, src/components/input/useInputProps.ts, src/styles/primitives/colors.css, tailwind.config.js, yarn.lock
- Implement InputDate component
- Fix disabled input style on Firefox
Task: [APP-2730](https://aragonassociation.atlassian.net/browse/APP-2730)
-   [x] …
=> feat: APP-2730 - Implement InputDate component

CHANGELOG.md, package.json, src/components/avatars/avatar/avatar.stories.tsx, src/components/avatars/avatar/avatar.test.tsx, src/components/avatars/avatar/avatar.tsx, src/components/avatars/avatar/index.ts, src/components/avatars/index.ts, yarn.lock
- implement the Avatar component with stories and tests
Task: [APP-2710](https://aragonassociation.atlassian.net/browse/APP-2710)
-   [x] I have tested …
=> Feature: APP-2710 - Implement Avatar component

CHANGELOG.md, src/components/avatars/avatarIcon/avatarIcon.test.tsx, src/components/avatars/avatarIcon/avatarIcon.tsx
- updates tests and documentation for the `AvatarIcon`
Task: [APP-0000](https://aragonassociation.atlassian.net/browse/APP-0000)
-   [x] I have tested …
=> Fix: Avatar Icon tests & documentation

.husky/pre-commit, CHANGELOG.md, package.json, yarn.lock
- Update `husky` to v9 (see [migration guide](https://github.com/typicode/husky/releases/tag/v9.0.1)) …
=> feat: Update husky to v9

CHANGELOG.md, src/components/textAreas/index.ts, src/components/textAreas/textArea/index.ts, src/components/textAreas/textArea/textArea.stories.tsx, src/components/textAreas/textArea/textArea.test.tsx, src/components/textAreas/textArea/textArea.tsx
- Implement `TextArea` component
Task: [APP-2743](https://aragonassociation.atlassian.net/browse/APP-2743) …
=> feat: APP-2743 - Implement TextArea component

jira_test.txt
Please include a summary of the change and be sure you follow the contributions rules we do provide
[here](./CONTRIBUTIONS.md)
Task: https://aragonassociation.atlassian.net/browse/APP-2875
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] I have selected the correct base branch.
-   [ ] I have performed a self-review of my own code.
-   [ ] My changes generate no new warnings.
-   [ …
=> APP-2875 Create jira_test.txt

CHANGELOG.md, src/components/checkbox/checkboxCard/checkboxCard.stories.tsx, src/components/checkbox/checkboxCard/checkboxCard.test.tsx, src/components/checkbox/checkboxCard/checkboxCard.tsx, src/components/checkbox/checkboxCard/index.ts, src/components/checkbox/checkboxGroup/checkboxGroup.stories.tsx, src/components/checkbox/checkboxGroup/checkboxGroup.tsx, src/components/checkbox/index.ts, src/components/radioGroup/radioCard/radioCard.stories.tsx, src/components/radioGroup/radioCard/radioCard.tsx
- Implement CheckboxCard component
- Fix unchecked / disabled style of RadioCard component
Task: [APP-2718](https://aragonassociation.atlassian.net/browse/APP-2718)
the …
=> feat: APP-2718 - Implement CheckboxCard component

CHANGELOG.md, package.json, src/components/index.ts, src/components/tooltip/index.ts, src/components/tooltip/tooltip.stories.tsx, src/components/tooltip/tooltip.test.tsx, src/components/tooltip/tooltip.tsx, yarn.lock
- Implements the `Tooltip` component
Task: [APP-2745](https://aragonassociation.atlassian.net/browse/APP-2745)
-   [ ] I have tested my code on the …
=> feat: APP-2745 - Implement Tooltip component

CHANGELOG.md, src/components/progress/progress.tsx
- Fix width of `Progress` component
=> fix: Fix width of Progress component

CHANGELOG.md, package.json, src/components/button/button.tsx, src/components/dropdown/dropdownContainer.stories.tsx, src/components/dropdown/dropdownContainer.test.tsx, src/components/dropdown/dropdownContainer.tsx, src/components/dropdown/dropdownItem.stories.tsx, src/components/dropdown/dropdownItem.test.tsx, src/components/dropdown/dropdownItem.tsx, src/components/dropdown/index.ts, src/components/index.ts, yarn.lock
- Implement `Dropdown` component
Task: [APP-2720](https://aragonassociation.atlassian.net/browse/APP-2720) …
=> feat: APP-2720 - Implement Dropdown component

CHANGELOG.md, package.json, src/components/dialogs/dialog/dialogContent/dialogContent.stories.tsx, src/components/dialogs/dialog/dialogContent/dialogContent.test.tsx, src/components/dialogs/dialog/dialogContent/dialogContent.tsx, src/components/dialogs/dialog/dialogContent/index.ts, src/components/dialogs/dialog/dialogFooter/dialogFooter.stories.tsx, src/components/dialogs/dialog/dialogFooter/dialogFooter.test.tsx, src/components/dialogs/dialog/dialogFooter/dialogFooter.tsx, src/components/dialogs/dialog/dialogFooter/index.ts, src/components/dialogs/dialog/dialogHeader/dialogHeader.stories.tsx, src/components/dialogs/dialog/dialogHeader/dialogHeader.test.tsx, src/components/dialogs/dialog/dialogHeader/dialogHeader.tsx, src/components/dialogs/dialog/dialogHeader/index.ts, src/components/dialogs/dialog/dialogRoot/dialogRoot.stories.tsx, src/components/dialogs/dialog/dialogRoot/dialogRoot.test.tsx, src/components/dialogs/dialog/dialogRoot/dialogRoot.tsx, src/components/dialogs/dialog/dialogRoot/index.ts, src/components/dialogs/dialog/index.ts, src/components/dialogs/index.ts, yarn.lock
- implements the `Dialog` component
Task: [APP-2911](https://aragonassociation.atlassian.net/browse/APP-2911)
-   [ ] I have tested my code on the test …
=> Feat: APP-2911 - Implement Dialog component

CHANGELOG.md, src/components/input/inputNumber/inputNumber.test.tsx, src/components/input/inputNumber/inputNumber.tsx
use correct icon 
Task: [APP-0000](https://aragonassociation.atlassian.net/browse/APP-0000)
=> fix: Use correct "MINUS" icon for InputNumber component

CHANGELOG.md, package.json, src/core/components/dialogs/dialog/dialogRoot/dialogRoot.tsx, src/core/components/dialogs/dialogAlert/dialogAlertRoot/dialogAlertRoot.tsx, src/core/components/dialogs/dialogUtils.ts, yarn.lock
- adds animations for the `Dialog` and `DialogAlert` components
-   [ ] I have tested my code on the test network.
=> feat: Implement Dialog animations

CHANGELOG.md, src/index.ts, src/modules/components/dao/daoAvatar/daoAvatar.stories.tsx, src/modules/components/dao/daoAvatar/daoAvatar.test.tsx, src/modules/components/dao/daoAvatar/daoAvatar.tsx, src/modules/components/dao/daoAvatar/index.ts, src/modules/components/dao/index.ts, src/modules/components/index.ts, src/modules/index.ts
- Implements `DaoAvatar` module component
Task: [APP-2939](https://aragonassociation.atlassian.net/browse/APP-2939)
-   [x] I have tested my code on …
=> feat: APP-2939 - Implement DaoAvatar module component

.storybook/preview.tsx, CHANGELOG.md, package.json, src/modules/components/index.ts, src/modules/components/odsModulesProvider/index.ts, src/modules/components/odsModulesProvider/odsModulesProvider.mdx, src/modules/components/odsModulesProvider/odsModulesProvider.test.tsx, src/modules/components/odsModulesProvider/odsModulesProvider.tsx, src/modules/index.mdx, src/modules/index.ts, src/modules/types/index.ts, src/modules/types/web3ComponentConfig.ts, yarn.lock
- Implement OdsModulesProvider for using wagmi hooks
- Update documentation
- Update required dependencies, move `react` and `react-dom` to peer dependencies
Task: [APP-2940](https://aragonassociation.atlassian.net/browse/APP-2940)
-   [ ] I ran all tests with success and extended them if necessary.
-   [x] I have updated the `CHANGELOG.md` file in the root …
=> feat: APP-2940 - Implement OdsModulesProvider for using wagmi hooks

.eslintrc.js, CHANGELOG.md, src/core/components/dialogs/dialog/dialogHeader/dialogHeader.tsx, src/core/components/dialogs/dialog/dialogRoot/dialogRoot.tsx, src/core/components/dialogs/dialogAlert/dialogAlertFooter/dialogAlertFooter.tsx, src/core/components/dialogs/dialogAlert/dialogAlertRoot/dialogAlertRoot.tsx, src/core/components/input/inputFileAvatar/inputFileAvatar.tsx
- Update eslint rules to align usage of boolean properties (prefer explicit boolean values)
**Note**: to be discussed
-   [x] I have tested my code on …
=> chore: Update eslint rules to align usage of boolean props

CHANGELOG.md, package.json, yarn.lock
- Update @testing-library/react to v15
=> chore: Update @testing-library/react to v15

CHANGELOG.md, src/core/components/states/index.ts, src/core/components/states/stateSkeletonBar/index.ts, src/core/components/states/stateSkeletonBar/stateSkeletonBar.stories.tsx, src/core/components/states/stateSkeletonBar/stateSkeletonBar.test.tsx, src/core/components/states/stateSkeletonBar/stateSkeletonBar.tsx, src/core/components/states/stateSkeletonCircular/index.ts, src/core/components/states/stateSkeletonCircular/stateSkeletonCircular.stories.tsx, src/core/components/states/stateSkeletonCircular/stateSkeletonCircular.test.tsx, src/core/components/states/stateSkeletonCircular/stateSkeletonCircular.tsx
- implements the StateSkeletonBar and StateSkeletonCircular core components
Task: [APP-3054](https://aragonassociation.atlassian.net/browse/APP-3054)
- …
=> feat: APP-3054 - Implement StateSkeletonBar & StateSkeletonCircular core components

CHANGELOG.md, src/modules/components/proposal/proposalDataListItem/index.ts, src/modules/components/proposal/proposalDataListItem/proposalDataListItemSkeleton/index.ts, src/modules/components/proposal/proposalDataListItem/proposalDataListItemSkeleton/proposalDataListItemSkeleton.stories.tsx, src/modules/components/proposal/proposalDataListItem/proposalDataListItemSkeleton/proposalDataListItemSkeleton.test.tsx, src/modules/components/proposal/proposalDataListItem/proposalDataListItemSkeleton/proposalDataListItemSkeleton.tsx, src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.tsx
- Implement `ProposalDataListItemSkeleton` module component
Task: [APP-2990](https://aragonassociation.atlassian.net/browse/APP-2990)
-   [ ] I have …
=> feat: APP-2990 - Implement ProposalDataListItemSkeleton module component

CHANGELOG.md, src/core/components/dataList/dataListContainer/dataListContainer.tsx, src/core/components/dataList/dataListFilter/dataListFilterStatus.tsx, src/core/components/dataList/dataListPagination/dataListPagination.tsx, src/core/components/dataList/dataListRoot/dataListRoot.tsx
- update DataList padding to allow component to use full container width
Task: [APP-3100](https://aragonassociation.atlassian.net/browse/APP-3100)
- …
=> feat:  APP-3100 - Remove DataList padding

.github/workflows/library-publish.yml, .github/workflows/library-release.yml, .github/workflows/library-test.yml, .github/workflows/storybook-preview-deploy.yml, .github/workflows/storybook-preview-remove.yml, .github/workflows/storybook-publish.yml, CHANGELOG.md, package.json, src/core/components/dataList/dataListContext/dataListContext.test.tsx, yarn.lock
- Update Node from 18 to 20
- Bump `actions/checkout` action to v4
- Fix warnings on workflows
=> chore: Update Node to v20, bump actions/checkout to v4, fix warnings on workflows

CHANGELOG.md, package.json, src/core/components/accordion/accordionContainer/accordionContainer.stories.tsx, src/core/components/documentParser/documentParser.stories.tsx, src/core/components/documentParser/documentParser.test.tsx, src/core/components/documentParser/documentParser.tsx, src/core/components/documentParser/index.ts, src/core/components/index.ts, tailwind.config.js, yarn.lock
Implements wrapper component which can receive markdown or HTML docs as strings and sanitize the output while styling with Tailwind typography plugin.
Task: [APP-3057](https://aragonassociation.atlassian.net/browse/APP-3057)
-   [x] I have updated the `CHANGELOG.md` file in the root folder …
=> feat: APP-3057 - Implement DocumentParser core component

CHANGELOG.md, src/core/components/index.ts
- Exports the `DefinitionList` core component
-   [ ] I have tested my code on the test …
=> fix: Export DefinitionList core component

CHANGELOG.md, package.json
- Update library exports to support require calls
=> fix: Update library exports to support require calls

CHANGELOG.md, src/core/components/collapsible/collapsible.api.ts, src/core/components/index.ts
- Export Collapsible core component
=> fix: Export Collabsible core component

CHANGELOG.md, src/core/components/dataList/dataListContainer/dataListContainer.tsx, src/core/components/dataList/dataListRoot/dataListRoot.stories.tsx
-   Handle new `layoutClassName` property on `DataList.Container` component to simplify implementation of custom
`DataList` layouts
-   [x] I have …
=> feat: Add "layoutClassName" property on DataList.Container component

CHANGELOG.md, src/core/components/dropdown/dropdownContainer/dropdownContainer.stories.tsx, src/core/components/dropdown/dropdownContainer/dropdownContainer.test.tsx, src/core/components/dropdown/dropdownContainer/dropdownContainer.tsx
- Update Dropdown component to support custom max width
Task: [APP-3189](https://aragonassociation.atlassian.net/browse/APP-3189)
-   [x] I have tested …
=> feat(APP-3189): Update Dropdown component to support custom max width

CHANGELOG.md, src/core/components/dialogs/dialog/dialogHeader/dialogHeader.stories.tsx, src/core/components/dialogs/dialog/dialogRoot/dialogRoot.stories.tsx, src/core/components/dialogs/dialogAlert/dialogAlertFooter/dialogAlertFooter.stories.tsx, src/core/components/dialogs/dialogAlert/dialogAlertHeader/dialogAlertHeader.stories.tsx, src/core/components/dialogs/dialogAlert/dialogAlertRoot/dialogAlertRoot.stories.tsx, src/core/components/dropdown/dropdownContainer/dropdownContainer.stories.tsx, src/core/components/forms/checkbox/checkbox.stories.tsx, src/core/components/forms/inputNumber/inputNumber.stories.tsx, src/core/components/forms/inputNumberMax/inputNumberMax.stories.tsx, src/core/components/forms/inputSearch/inputSearch.stories.tsx, src/core/components/forms/inputText/inputText.stories.tsx, src/core/components/forms/inputTime/inputTime.stories.tsx, src/core/components/forms/radioGroup/radioGroup/radioGroup.stories.tsx, src/core/components/forms/switch/switch.stories.tsx, src/core/components/forms/textArea/textArea.stories.tsx, src/core/components/forms/textAreaRichText/textAreaRichText.stories.tsx, src/core/components/toggles/toggleGroup/toggleGroup.stories.tsx, src/core/components/tooltip/tooltip.stories.tsx, src/modules/components/address/addressInput/addressInput.stories.tsx
Reduced the use of controlled components in stories to improve code visibility in Storybook
Task: [APP-2886](https://aragonassociation.atlassian.net/browse/APP-2886)
-   [x] I ran all tests with …
=> chore(APP-2886): Reduce the use of controlled components in stories to improve code visibility in Storybook

CHANGELOG.md, src/core/assets/copy/coreCopy.ts, src/core/components/dataList/dataListFilter/dataListFilter.tsx, src/core/components/dataList/dataListFilter/dataListFilterStatus.test.tsx, src/core/components/dataList/dataListFilter/dataListFilterStatus.tsx, src/core/components/dataList/dataListRoot/dataListRoot.stories.tsx
- Add functionality to reset all filters in `DataListFilter` core component.
- Add additional tests to ensure button is rendered correctly (when status === 'filtered') and to ensure `onResetFiltersClick` callback is called correctly.
Task: [APP-2929](https://aragonassociation.atlassian.net/browse/APP-2928)
-   [x] My …
=> feat(APP-2928): Add reset filter functionality to DataListFilter core component

CHANGELOG.md, src/modules/components/address/addressInput/addressInput.tsx, src/modules/components/asset/assetTransfer/assetTransfer.tsx, src/modules/hooks/useBlockExplorer/index.ts, src/modules/hooks/useBlockExplorer/useBlockExplorer.test.ts, src/modules/hooks/useBlockExplorer/useBlockExplorer.ts
- Update `useExplorerHook` to return information about the block explorer
=> feat: Update useBlockExplorer hook to return information about the block explorer

CHANGELOG.md, src/core/components/progress/progress.api.ts, src/core/components/progress/progress.stories.tsx, src/core/components/progress/progress.test.tsx, src/core/components/progress/progress.tsx
- Rename `indicator` property to `thresholdIndicator` on Progress component
Task: [APP-3346](https://aragonassociation.atlassian.net/browse/APP-3346)
-   [x] I …
=> fix(APP-3346): Rename progress indicator property to thresholdIndicator

CHANGELOG.md, src/modules/components/asset/assetTransfer/assetTransfer.tsx, src/modules/components/asset/assetTransfer/assetTransferAddress/assetTransferAddress.tsx, src/modules/components/member/memberAvatar/memberAvatar.test.tsx, src/modules/components/member/memberAvatar/memberAvatar.tsx, src/modules/components/proposal/proposalActions/actions/proposalActionChangeMembers/proposalActionChangeMembers.tsx, src/modules/components/proposal/proposalActions/actions/proposalActionTokenMint/proposalActionTokenMint.tsx, src/modules/components/vote/voteDataListItem/voteDataListItemStructure/voteDataListItemStructure.tsx, src/modules/components/wallet/wallet.stories.tsx, src/modules/components/wallet/wallet.test.tsx, src/modules/components/wallet/wallet.tsx, src/modules/types/compositeAddress.ts
- Update `ICompositeAddress` interface and components using it to support custom avatar
- Fix ENS name truncation on `Wallet` component
- Fix `Wallet` component to only resolve user ENS name when `name` property is not set
- Update `Wallet` component to support custom `chainId` and `wagmi` configurations …
=> fix: Minor fixes on Wallet component, support custom avatar on modules components

CHANGELOG.md, package.json, src/core/components/dialogs/dialog/dialogRoot/dialogRoot.tsx, src/core/components/dialogs/dialogAlert/dialogAlertRoot/dialogAlertRoot.tsx, src/core/components/forms/index.css, src/core/components/forms/textAreaRichText/index.css, src/core/components/forms/textAreaRichText/textAreaRichText.stories.tsx, src/core/components/forms/textAreaRichText/textAreaRichText.test.tsx, src/core/components/forms/textAreaRichText/textAreaRichText.tsx, src/core/components/index.css, yarn.lock
- Fix expand behaviour of TextAreaRichText component
Task: [APP-3494](https://aragonassociation.atlassian.net/browse/APP-3494)
-   [x] I have tested my code on …
=> fix(APP-3494): Fix expand behaviour of TextAreaRichText component

CHANGELOG.md, src/modules/assets/copy/modulesCopy.ts, src/modules/components/proposal/proposalActions/actions/generators/proposalActionChangeMembers.ts, src/modules/components/proposal/proposalActions/actions/generators/proposalActionTokenMint.ts, src/modules/components/proposal/proposalActions/actions/generators/proposalActionUpdateMetadata.ts, src/modules/components/proposal/proposalActions/actions/generators/proposalActionWithdrawToken.ts, src/modules/components/proposal/proposalActions/proposalActions/proposalActions.stories.tsx, src/modules/components/proposal/proposalActions/proposalActionsAction/proposalActionsAction.test.tsx, src/modules/components/proposal/proposalActions/proposalActionsAction/proposalActionsAction.tsx, src/modules/components/proposal/proposalActions/proposalActionsTypes/proposalAction.ts
Implements Alert Card with modules copy for title and description with Eth amount if value present in action
Task: [APP-3466](https://aragonassociation.atlassian.net/browse/APP-3466)
-   [ ] I have performed a self-review of my own code.
-   [x] I have updated the `CHANGELOG.md` file in the root folder of the package after the [UPCOMING] title …
=> feat(APP-3466): Implement alert for proposal actions which send native currency

CHANGELOG.md, src/modules/components/odsModulesProvider/odsModulesProvider.tsx
- Update OdsModulesProvider to support wagmiInitialState config
Task: [APP-3512](https://aragonassociation.atlassian.net/browse/APP-3512)
-   [x] I …
=> feat(APP-3512): Update OdsModulesProvider to support wagmiInitialState config

CHANGELOG.md, src/modules/components/proposal/proposalActions/actions/generators/proposalActionTokenMint.ts, src/modules/components/proposal/proposalActions/actions/proposalActionTokenMint/proposalActionTokenMint.stories.tsx, src/modules/components/proposal/proposalActions/actions/proposalActionTokenMint/proposalActionTokenMint.test.tsx, src/modules/components/proposal/proposalActions/actions/proposalActionTokenMint/proposalActionTokenMint.tsx, src/modules/components/proposal/proposalActions/proposalActionsTypes/proposalActionTokenMint.ts
Remove Summary from ProposalActionTokenMint, update tests and other support files
-   [x]  My changes generate no new warnings.
=> fix: Update ProposalActionTokenMint - remove 'Summary', update tests, make receiver singular

CHANGELOG.md, src/modules/components/wallet/wallet.test.tsx, src/modules/components/wallet/wallet.tsx
- Update Wallet component to propagate chainId and wagmi config to MemberAvatar component
=> fix: Update Wallet component to propagate chainId and wagmi config to MemberAvatar component

CHANGELOG.md, src/core/components/dialogs/dialog/dialogFooter/dialogFooter.tsx, src/core/components/dialogs/dialogAlert/dialogAlertFooter/dialogAlertFooter.tsx, src/core/components/spinner/spinner.stories.tsx, src/core/components/spinner/spinner.test.tsx, src/core/components/spinner/spinner.tsx
- Support isLoading property on Spinner component and disabled / isLoading properties on DialogFooter components …
=> feat: Support isLoading property on Spinner component and disabled / isLoading properties on DialogFooter components

CHANGELOG.md, src/core/components/accordion/accordionItem/accordionItem.tsx, src/core/components/states/emptyState/emptyState.tsx, src/modules/assets/copy/modulesCopy.ts, src/modules/components/proposal/proposalActions/proposalActions/proposalActions.stories.tsx, src/modules/components/proposal/proposalActions/proposalActions/proposalActions.test.tsx, src/modules/components/proposal/proposalActions/proposalActions/proposalActions.tsx, src/modules/components/proposal/proposalActions/proposalActionsAction/proposalActionsAction.tsx
- Add EmptyState fallback for ProposalActions
- Tighten up EmptyState layout to center heading and description
- Handle optional Heading for ProposalActions with border …
=> feat(APP-3516): Update ProposalActions for EmptyState fallback

CHANGELOG.md, src/modules/components/vote/voteProposalDataListItem/voteProposalDataListItemStructure/voteProposalDataListItemStructure.tsx
Fix truncation issue on `<VoteProposalDateListItemStructure />` component
Task: [APP-3490](https://aragonassociation.atlassian.net/browse/APP-3490)
-   [x ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] I ran all tests with success and …
=> Add truncation to vote proposal item

CHANGELOG.md, src/modules/assets/copy/modulesCopy.ts, src/modules/components/proposal/proposalUtils.ts, src/modules/components/proposal/proposalVoting/proposalVotingStageStatus/proposalVotingStageStatus.test.tsx, src/modules/components/proposal/proposalVoting/proposalVotingStageStatus/proposalVotingStageStatus.tsx
Add support for Vetoed status in ProposalVotingStageStatus
Task: [APP-3627](https://aragonassociation.atlassian.net/browse/APP-3627) …
=> fix(APP-3627): Add support for Vetoed status in ProposalVotingStageStatus

CHANGELOG.md, src/modules/components/proposal/proposalVoting/proposalVotingDetails/proposalVotingDetails.stories.tsx, src/modules/components/proposal/proposalVoting/proposalVotingDetails/proposalVotingDetails.test.tsx, src/modules/components/proposal/proposalVoting/proposalVotingDetails/proposalVotingDetails.tsx, src/modules/components/proposal/proposalVoting/proposalVotingStage/proposalVotingStage.tsx, src/modules/components/proposal/proposalVoting/proposalVotingStageStatus/proposalVotingStageStatus.test.tsx, src/modules/components/proposal/proposalVoting/proposalVotingStageStatus/proposalVotingStageStatus.tsx
Add support for - override for start and end time when it is unknown
Task: [APP-3664](https://aragonassociation.atlassian.net/browse/APP-3664)
-   [x] I ran all tests with success and extended …
=> fix(APP-3664): Add support for - override for start and end time when it is unknown

CHANGELOG.md, src/modules/components/vote/voteProposalDataListItem/voteProposalDataListItemStructure/voteProposalDataListItemStructure.stories.tsx, src/modules/components/vote/voteProposalDataListItem/voteProposalDataListItemStructure/voteProposalDataListItemStructure.tsx
- Fix VoteProposalDataListItem module component to truncate long proposal IDs
Task: [APP-3626](https://aragonassociation.atlassian.net/browse/APP-3626)
-   [x] …
=> fix(APP-3626): Fix VoteProposalDataListItem module component to truncate long proposal IDs

CHANGELOG.md, src/core/components/alerts/alertUtils.ts
Task: https://aragonassociation.atlassian.net/browse/APP-3632
-   [X] Bug fix (non-breaking change which fixes an issue)
-   [X] I have selected the correct base branch.
-   [X] I have performed a self-review of my own code.
-   [X] My changes generate no new warnings.
-   [ ] I ran all tests with success and extended them if necessary.
-   [ ] I have updated the `CHANGELOG.md` file in the root folder of the package after the [UPCOMING] title and before
-   [ ] I have tested my code on the test network.
=> fix(APP-3632): Implements correct icon for critical alerts

CHANGELOG.md, src/core/components/cards/card/card.tsx, src/core/components/cards/cardEmptyState/cardEmptyState.tsx, src/modules/components/proposal/proposalActions/proposalActionsContainer/proposalActionsContainer.tsx, src/modules/components/proposal/proposalVoting/proposalVotingStage/proposalVotingStage.tsx
- Fix empty-state style of ProposalAction module component
Task: [APP-3666](https://aragonassociation.atlassian.net/browse/APP-3666)
-   [x] I have tested my …
=> fix(APP-3666): Fix empty-state style of ProposalAction module component

CHANGELOG.md, package.json, yarn.lock
- Update peer dependencies to allow React 19
=> feat: Update peer dependencies to allow React 19

CHANGELOG.md, src/core/components/forms/checkboxCard/checkboxCard.tsx, src/modules/components/address/addressInput/addressInput.tsx
- Fix re-render issue on `<AddressInput />` module component when `onAccept` prop changes on every render
- Update `<CheckboxCard />` core component to set full-width to `children` property wrapper
=> fix: Fix re-render issue on AddressInput component, fix style of CheckboxCard children wrapper

CHANGELOG.md, src/core/components/dialogs/dialog/dialogHeader/dialogHeader.tsx
- Update DialogHeader component to not truncate description strings
Task: [APP-3615](https://aragonassociation.atlassian.net/browse/APP-3615)
[APP-3615]: https://aragonassociation.atlassian.net/browse/APP-3615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(APP-3615): Update DialogHeader component to not truncate description strings

CHANGELOG.md, src/theme/tokens/primitives/borderRadius.mdx, src/theme/tokens/primitives/colors.mdx, src/theme/tokens/primitives/shadows.mdx, src/theme/tokens/primitives/spacing.mdx, src/theme/tokens/primitives/typography.mdx
- Fix documentation pages on primitive variables
=> fix: Fix documentation pages on primitive variables

CHANGELOG.md, src/modules/components/dao/daoDataListItem/daoDataListItemStructure/daoDataListItemStructure.stories.tsx, src/modules/components/dao/daoDataListItem/daoDataListItemStructure/daoDataListItemStructure.test.tsx, src/modules/components/dao/daoDataListItem/daoDataListItemStructure/daoDataListItemStructure.tsx
- Update DaoDataListItem component to support isExternal property
- Truncate address of DAO on item component
=> feat: Update DaoDataListItem component to support isExternal property

CHANGELOG.md, src/modules/components/asset/assetDataListItem/assetDataListItemStructure/assetDataListItemStructure.stories.tsx, src/modules/components/asset/assetDataListItem/assetDataListItemStructure/assetDataListItemStructure.test.tsx, src/modules/components/asset/assetDataListItem/assetDataListItemStructure/assetDataListItemStructure.tsx
- Update AssetDataListItem component to support hideValue property
Task: [APP-3652](https://aragonassociation.atlassian.net/browse/APP-3652)
[APP-3652]: https://aragonassociation.atlassian.net/browse/APP-3652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(APP-3652): Update AssetDataListItem component to support hideValue property

CHANGELOG.md, src/modules/components/dao/daoDataListItem/daoDataListItemStructure/daoDataListItemStructure.stories.tsx, src/modules/components/dao/daoDataListItem/daoDataListItemStructure/daoDataListItemStructure.tsx
Update DAO name vertical alignment in `DaoDataListItem` to be centred in the case when no address nor ENS is provided.
Task: [APP-4065](https://aragonassociation.atlassian.net/browse/APP-4065)
[APP-4065]: https://aragonassociation.atlassian.net/browse/APP-4065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(APP-4065): Update DAO name vertical alignment in DaoDataListItem

.github/workflows/library-publish.yml, .github/workflows/library-release.yml, .github/workflows/library-test.yml, .github/workflows/storybook-preview-deploy.yml, .github/workflows/storybook-preview-remove.yml, .github/workflows/storybook-publish.yml, CHANGELOG.md, package.json, src/core/utils/formatterUtils/formatterUtils.test.ts
- Update configs to use Node v22
=> chore: Update configs to use Node v22

CHANGELOG.md, src/core/components/dialogs/dialog/dialogRoot/dialogRoot.tsx
Removes overflow from root dialogs
=> fix: Remove overflow from DialogRoot

.changeset/polite-memes-clean.md, .github/workflows/shared-deploy.yml
- Update Storybook deploy workflow to retrieve secrets from 1Password
=> chore: Update Storybook deploy workflow to retrieve secrets from 1Password

.changeset/some-walls-vanish.md, src/modules/components/address/addressInput/addressInput.test.tsx, src/modules/components/address/addressInput/addressInput.tsx, src/modules/components/asset/assetTransfer/assetTransfer.test.tsx, src/modules/components/asset/assetTransfer/assetTransfer.tsx, src/modules/components/gukModulesProvider/gukModulesProvider.tsx, src/modules/components/member/memberAvatar/memberAvatar.stories.tsx, src/modules/components/member/memberAvatar/memberAvatar.test.tsx, src/modules/components/member/memberAvatar/memberAvatar.tsx, src/modules/components/proposal/proposalActions/proposalActionsItem/proposalActionsItem.test.tsx, src/modules/components/proposal/proposalActions/proposalActionsItem/proposalActionsItem.tsx, src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionChangeMembers/proposalActionChangeMembers.test.tsx, src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionTokenMint/proposalActionTokenMint.test.tsx, src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.api.ts, src/modules/components/proposal/proposalDataListItem/proposalDataListItemStructure/proposalDataListItemStructure.tsx, src/modules/components/wallet/wallet.test.tsx, src/modules/components/wallet/wallet.tsx, src/modules/types/web3ComponentConfig.ts
- Update module components to set ethereum mainnet as default value for chain-id property
Task: [APP-4207](https://aragonassociation.atlassian.net/browse/APP-4207)
[APP-4207]: https://aragonassociation.atlassian.net/browse/APP-4207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(APP-4207): Update module components to set ethereum mainnet as default value for chain-id property

.changeset/small-tips-pick.md, .changeset/social-beds-like.md, src/core/components/definitionList/definitionListItem/definitionListItem.stories.tsx, src/core/components/definitionList/definitionListItem/definitionListItem.tsx, src/core/components/link/link/link.api.ts, src/core/components/link/link/link.stories.tsx, src/core/components/link/link/link.test.tsx, src/core/components/link/link/link.tsx, src/modules/components/proposal/proposalActions/proposalActionsItem/proposalActionsItem.tsx, src/modules/components/proposal/proposalActions/proposalActionsList/proposalActionUpdateMetadata/proposalActionUpdateMetadata.tsx
Update Link component with following:
- Update right icon spacing
- Add `showUrl` flag to enable showing the URL of the link as help text
- Add `isExternal` flag to automatically add proper target and right icon
- Remove `description` prop [BREAKING CHANGE]
- Update colors
Other updates:
- Add `description` prop to DefinitionListItem
- `DefinitionListItem` `leading-tight` -> `leading-normal`
Task: [APP-4232](https://aragonassociation.atlassian.net/browse/APP-4232)
Task: [APP-3986](https://aragonassociation.atlassian.net/browse/APP-3986)
[APP-4232]: https://aragonassociation.atlassian.net/browse/APP-4232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-3986]: https://aragonassociation.atlassian.net/browse/APP-3986?atlOrigin=eyJpIjoiNWRkNTljNz …
=> feat(APP-4232): Update link component to support isExternal and showUrl flags

.changeset/slimy-ends-open.md, .changeset/twelve-streets-study.md, src/core/components/definitionList/definitionListItem/definitionListItem.stories.tsx, src/core/components/definitionList/definitionListItem/definitionListItem.test.tsx, src/core/components/definitionList/definitionListItem/definitionListItem.tsx, src/core/components/definitionList/definitionListItem/definitionListItemContent.test.tsx, src/core/components/definitionList/definitionListItem/definitionListItemContent.tsx, src/modules/assets/copy/modulesCopy.ts, src/modules/components/proposal/proposalVoting/proposalVoting.stories.tsx, src/modules/components/proposal/proposalVoting/proposalVotingBodyContent/proposalVotingBodyContent.test.tsx, src/modules/components/proposal/proposalVoting/proposalVotingBodySummary/proposalVotingBodySummary.test.tsx, src/modules/components/proposal/proposalVoting/proposalVotingBodySummaryListItem/proposalVotingBodySummaryListItem.test.tsx, src/modules/components/proposal/proposalVoting/proposalVotingBreakdownMultisig/proposalVotingBreakdownMultisig.stories.tsx, src/modules/components/proposal/proposalVoting/proposalVotingBreakdownMultisig/proposalVotingBreakdownMultisig.test.tsx, src/modules/components/proposal/proposalVoting/proposalVotingBreakdownMultisig/proposalVotingBreakdownMultisig.tsx, src/modules/components/proposal/proposalVoting/proposalVotingBreakdownToken/proposalVotingBreakdownToken.tsx, src/modules/components/proposal/proposalVoting/proposalVotingDetails/proposalVotingDetails.stories.tsx, src/modules/components/proposal/proposalVoting/proposalVotingDetails/proposalVotingDetails.test.tsx, src/modules/components/proposal/proposalVoting/proposalVotingDetails/proposalVotingDetails.tsx, src/modules/components/proposal/proposalVoting/proposalVotingProgress/proposalVotingProgress.stories.tsx, src/modules/components/proposal/proposalVoting/proposalVotingProgress/proposalVotingProgressItem.test.tsx, src/modules/components/proposal/proposalVoting/proposalVotingProgress/proposalVotingProgressItem.tsx, src/modules/components/proposal/proposalVoting/proposalVotingStage/proposalVotingStage.tsx, src/modules/components/proposal/proposalVoting/proposalVotingStageContext/proposalVotingStageContext.test.tsx, src/modules/components/proposal/proposalVoting/proposalVotingStageContext/proposalVotingStageContext.ts, src/modules/components/proposal/proposalVoting/proposalVotingTabs/proposalVotingTabs.test.tsx, src/modules/types/definitionSetting.ts
- Update parameters and info displayed on ProposalVoting module component
- Update `DefinitionListItem` component to support `copyValue` property
Task: [APP-3636](https://aragonassociation.atlassian.net/browse/APP-3636)
App PR: [#593](https://github.com/aragon/app-next/pull/593)
[APP-3636]: https://aragonassociation.atlassian.net/browse/APP-3636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(APP-3636): Update parameters and info displayed on ProposalVoting module component

.changeset/tender-eggs-speak.md, src/modules/components/proposal/proposalVoting/proposalVotingStageStatus/proposalVotingStageStatusAdvanceable.tsx
Update ProposalVotingStageStatusAdvanceable to rerender and correctly update statuses
Task: [APP-3841](https://aragonassociation.atlassian.net/browse/APP-3841)
[APP-3841]: https://aragonassociation.atlassian.net/browse/APP-3841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(APP-3841): Update ProposalVotingStageStatusAdvanceable to rerender and correctly update statuses

.changeset/fruity-ways-dress.md, src/core/components/forms/textAreaRichText/textAreaRichText.test.tsx, src/core/components/forms/textAreaRichText/textAreaRichText.tsx
https://aragonassociation.atlassian.net/browse/APP-3755
[APP-3841]: https://aragonassociation.atlassian.net/browse/APP-3841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(APP-3755): Fix TextAreaRichText core component to format markdown text pasted from the clipboard 

.changeset/all-turtles-yell.md, .github/workflows/library-publish.yml, .github/workflows/library-release.yml, .github/workflows/library-snapshot.yml, .github/workflows/storybook-preview.yml
=> chore: Update release workflow

.changeset/flat-breads-jam.md, src/modules/components/index.ts, src/modules/components/smartContract/index.ts
Fix export of SmartContractFunctionDataListItem component
Task: [APP-4405](https://aragonassociation.atlassian.net/browse/APP-4405)
[APP-4405]: https://aragonassociation.atlassian.net/browse/APP-4405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(APP-4405): Fix export of SmartContractFunctionDataListItem component
